version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    restart: unless-stopped

  fastapi:
    image: ameurelmoukh/fastapi_translation:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  ollama_data:
